# Site Info
title: 法天贵真
tagline: '人能常清静,天地悉皆归.'
description: 'A Jekyll theme made by <a href="http://zzyn.github.io" target="_blank">@Zack Zou</a>.'
baseurl: ""
url: http://zzyn.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Zack Zou
  description: A Fullstack Engineer and <strong>Designer</strong>.
  gravatar: e81924facb09b0d3edd80ad170cd9e22 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/zongyin/
    github:    https://github.com/zzyn
    # facebook:  <hide>
    # twitter:   
    # weibo:     
    email:     mailto:zzyn125@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://github.com/zzyn'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/qingjing.png
  caption: 清静经 &copy; 人能常清静,天地悉皆归.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token:  # leave blank if you don't want google analytics
disqus_short_name: 'zzyn' # leave blank if you don't want disqus

